/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.up.edu.java.ejemplo.diez.vista;

/**
 *
 * @author ESTUDIANTE
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuPersona = new javax.swing.JMenu();
        menuCrearPersona = new javax.swing.JMenuItem();
        menuActualizarPersona = new javax.swing.JMenuItem();
        menuBuscarPersona = new javax.swing.JMenuItem();
        menuEliminarPersona = new javax.swing.JMenuItem();
        menuListarPersona = new javax.swing.JMenuItem();
        MenuOperadora = new javax.swing.JMenu();
        menuCrearOperadora = new javax.swing.JMenuItem();
        menuActualizarOperadora = new javax.swing.JMenuItem();
        menuBuscarOperadora = new javax.swing.JMenuItem();
        menuElimnarOperadora = new javax.swing.JMenuItem();
        menuListarOperadora = new javax.swing.JMenuItem();
        menuTelefono = new javax.swing.JMenu();
        menuCrearTelefono = new javax.swing.JMenuItem();
        MenuActualizarTelefono = new javax.swing.JMenuItem();
        MenuBuscarTelefono = new javax.swing.JMenuItem();
        MenuEliminarTelefono = new javax.swing.JMenuItem();
        MenuListarTelefono = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPersona.setMnemonic('f');
        MenuPersona.setText("Persona");

        menuCrearPersona.setMnemonic('o');
        menuCrearPersona.setText("Crear");
        menuCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearPersonaActionPerformed(evt);
            }
        });
        MenuPersona.add(menuCrearPersona);

        menuActualizarPersona.setMnemonic('s');
        menuActualizarPersona.setText("Actualizar");
        MenuPersona.add(menuActualizarPersona);

        menuBuscarPersona.setMnemonic('a');
        menuBuscarPersona.setText("Buscar");
        MenuPersona.add(menuBuscarPersona);

        menuEliminarPersona.setMnemonic('x');
        menuEliminarPersona.setText("Eliminar");
        MenuPersona.add(menuEliminarPersona);

        menuListarPersona.setText("LIstar");
        menuListarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarPersonaActionPerformed(evt);
            }
        });
        MenuPersona.add(menuListarPersona);

        menuBar.add(MenuPersona);

        MenuOperadora.setMnemonic('e');
        MenuOperadora.setText("Operadora");

        menuCrearOperadora.setMnemonic('t');
        menuCrearOperadora.setText("Crear");
        MenuOperadora.add(menuCrearOperadora);

        menuActualizarOperadora.setMnemonic('y');
        menuActualizarOperadora.setText("Actualizar");
        MenuOperadora.add(menuActualizarOperadora);

        menuBuscarOperadora.setMnemonic('p');
        menuBuscarOperadora.setText("Buscar");
        MenuOperadora.add(menuBuscarOperadora);

        menuElimnarOperadora.setMnemonic('d');
        menuElimnarOperadora.setText("Elimnar");
        MenuOperadora.add(menuElimnarOperadora);

        menuListarOperadora.setText("Listar");
        MenuOperadora.add(menuListarOperadora);

        menuBar.add(MenuOperadora);

        menuTelefono.setMnemonic('h');
        menuTelefono.setText("Telefono");

        menuCrearTelefono.setMnemonic('c');
        menuCrearTelefono.setText("Crear");
        menuTelefono.add(menuCrearTelefono);

        MenuActualizarTelefono.setMnemonic('a');
        MenuActualizarTelefono.setText("Actualizar");
        menuTelefono.add(MenuActualizarTelefono);

        MenuBuscarTelefono.setText("Buscar");
        menuTelefono.add(MenuBuscarTelefono);

        MenuEliminarTelefono.setText("Eliminar");
        menuTelefono.add(MenuEliminarTelefono);

        MenuListarTelefono.setText("Listar");
        menuTelefono.add(MenuListarTelefono);

        menuBar.add(menuTelefono);

        jMenu1.setText("Salir");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCrearPersonaActionPerformed

    private void menuListarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListarPersonaActionPerformed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuActualizarTelefono;
    private javax.swing.JMenuItem MenuBuscarTelefono;
    private javax.swing.JMenuItem MenuEliminarTelefono;
    private javax.swing.JMenuItem MenuListarTelefono;
    private javax.swing.JMenu MenuOperadora;
    private javax.swing.JMenu MenuPersona;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuActualizarOperadora;
    private javax.swing.JMenuItem menuActualizarPersona;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuscarOperadora;
    private javax.swing.JMenuItem menuBuscarPersona;
    private javax.swing.JMenuItem menuCrearOperadora;
    private javax.swing.JMenuItem menuCrearPersona;
    private javax.swing.JMenuItem menuCrearTelefono;
    private javax.swing.JMenuItem menuEliminarPersona;
    private javax.swing.JMenuItem menuElimnarOperadora;
    private javax.swing.JMenuItem menuListarOperadora;
    private javax.swing.JMenuItem menuListarPersona;
    private javax.swing.JMenu menuTelefono;
    // End of variables declaration//GEN-END:variables

}
